#!/usr/bin/env bash
# 
# sshd-keys [ backupdir ]
# Backs up and regenerates host SSH keys
# set -x

BKUP=${1:-$( pwd )/backups}
pushd /etc > /dev/null
KEYFILES=$( ls -1 ssh/ssh_host*key* )
TS=`date +"%Y%m%d.%H%M"`

mkdir -p "$BKUP/ssh"
for OLD in $KEYFILES; do
  mv /etc/$OLD $BKUP/$OLD-$TS
  ERR=$?
  # If there was an error, restore the original file
  [ ! $ERR -a -f $BKUP/$OLD-$TS ] && mv -f $BKUP/$OLD-$TS /etc/$OLD
done

# echo "Restarting SSHd - this should trigger generation of new keys"
# service sshd restart 
ssh-keygen -f ssh/ssh_host_rsa_key     -N '' -t rsa
ssh-keygen -f ssh/ssh_host_dsa_key     -N '' -t dsa
ssh-keygen -f ssh/ssh_host_ecdsa_key   -N '' -t ecdsa
ssh-keygen -f ssh/ssh_host_ed22519_key -N '' -t ed25519
popd > /dev/null

exit $ERR
