#!/usr/bin/env bash

[ ! -d /usr/local/composer ] && mkdir -p /usr/local/composer
cd /usr/local/composer

EXPECTED_SIGNATURE=$(wget -q -O - https://composer.github.io/installer.sig)
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")

if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
then
    >&2 echo 'ERROR: Invalid installer signature'
    rm composer-setup.php
    exit 1
fi

php composer-setup.php --install-dir=/usr/local/composer --filename=composer && ln -s /usr/local/composer/composer /usr/local/bin/composer
RESULT=$?
rm composer-setup.php
exit $RESULT
