#!/usr/bin/env bash
S=${1:-$( hostname -s )}	# Selector
D=${2:-$( hostname -d )}	# Domain

[ -f /etc/opendkim.conf ] || apt install opendkim || exit 1
[ -x /usr/bin/opendkim-genkey ] || apt install opendkim-tools || exit 1

[ ! -d ./dkim ] && mkdir ./dkim
[   -f ./dkim/$S.private ] && { echo "Keys for the selector $S have already been created" ; exit 1 ; }

opendkim-genkey --directory=./dkim --verbose --domain=$D --selector=$S || exit 1

[ ! -d /etc/opendkim ] && mkdir /etc/opendkim
[ ! -d /etc/dkimkeys ] && mkdir /etc/dkimkeys

cp ./dkim/$S.private /etc/dkimkeys/$S.private
echo "$S._domainkey.$D	$D:$S:/etc/dkimkeys/$S.private" >> /etc/opendkim/keyfile
echo "*@$D	$S._domainkey.$D" >> /etc/opendkim/signing
chown -R opendkim:opendkim /etc/dkimkeys /etc/opendkim

./replace_file opendkim.conf
./replace_file default/opendkim
service opendkim restart

if [ ! -f /etc/postfix/main.cf ]; then
  echo "postfix configuration file not found!"
  exit 1
else
  grep "smtpd_milters = inet:localhost:8891" /etc/postfix/main.cf > /dev/null || cat tools/linode-etc/postfix/main.cf.opendkim >> /etc/postfix/main.cf
  service postfix restart
fi

echo
echo "DKIM configuration completed. Update DNS with information in `pwd`/dkim/$S.txt:"
echo
cat `pwd`/dkim/$S.txt
echo
